### ISSUE TITLE
Not building or attempting to build new floors

### ISSUE THREAD

**Issue by WeetbixNMilk** [filadog/TinyClicker#6]
My usage:
Bluestacks 5
Resolution 666 x 1184 fixed
VIP purchased and detected
Free bux menu minimised
Video ads disabled

Functionality:
All features work properly as stated except building new floors.

Issue:
Tinyclicker will not build new floors. It will fail building the new floor when passing the tutorial. It fails at any height of tower and will not rebuild once past 50.
I have tried setting the current floor to a range of -2, -1, 0, +1, +2 rebooting Tinyclicker after each time.
It neither attempts to build a new floor or builds one. I have left it running for a few hours once cycling settings.

Thanks.

**Comment by filadog** [comment]
Hey @WeetbixNMilk, thanks for the feedback, I've attempted to fix the issue in the [latest release.](https://github.com/filadog/TinyClicker/releases/tag/v1.5)
Download and copy archive content into TinyClicker folder. Replace files if asked.
Make sure to manually complete the tutorial if it's not finished and set the correct floor inside the clicker settings before running. 
Let me know if the issue is still present.
