### ISSUE TITLE
Nothing happens when running

### ISSUE THREAD

**Issue by shrekfx** [filadog/TinyClicker#7]
I could be a total dunce on this, but after following the steps and running the file, I can see the steps in the tinyclicker, but nothing happing in tiny tower.  All the clicking in the video is done by me, the app didn't do anything.  It wants to, but it wont. :(

Here is a link to a video capture of what is going one, it wouldn't let me upload it since it was to big of a file..

[https://filerun.photosandbrew.xyz/wl/?id=HEuBb1NClfPiEjWrGufP0y0I8JjS44w6](url)

**Comment by shrekfx** [comment]
Looks like you will have to just copy and paste the url, clicking it doesnt work either.

**Comment by filadog** [comment]
Hey @shrekfx, it definitely looks like a bug, I will look into it. May take some time

**Comment by shrekfx** [comment]
Awesome, no worries. Thanks for the quick response :)

**Comment by filadog** [comment]
@shrekfx I've tried to reproduce the issue but could not do that. 
First I would suggest selecting the emulator before pressing "Start", it might help.

Also try downloading a [more recent version of clicker from here](https://github.com/stereostas/TinyClicker/releases/tag/v1.9).
You may also manually make game window smaller by dragging the Bluestacks window, by ~1/3, and then launch and try the new version. Also make sure you launch only one Bluestacks instance, and not from the Multi-Instance manager.

Please let me know if the issue is still present after this.

And a side note: I see you set to rebuild at 70th floor, be careful as the clicker will rebuild immediately as it reaches this floor without any warning, and it will happen fast, so be sure to save your bitizens before that :)

**Comment by shrekfx** [comment]
@stereostas I'll try that.  Not sure what you mean by launching Bluesstacks instance, not from the Multi-instance manager.  

Here, I'll add this, this is what I do to start everything up, might help pin point what I'm doing wrong... Like I said, I'm a dunce LOL.

https://filerun.photosandbrew.xyz/wl/?id=Wnra6S9vI8qzYdAsmmAbZjXjZAD1c3xu

**Comment by filadog** [comment]
@shrekfx it seems you launch the correct version of Bluestacks, but the problem is with the emulator window.
Have you tried to resize the Bluestacks window and make it a bit smaller? 
There also should be a new file inside the TinyClicker folder, called log.txt, do you mind sharing it here? It does not contain any sensitive information, but might contain the error message.

**Comment by shrekfx** [comment]
[Config.txt](https://github.com/stereostas/TinyClicker/files/11242723/Config.txt)
[log.txt](https://github.com/stereostas/TinyClicker/files/11242724/log.txt)

I have tried to drag resize the window but that didn't work.

**Comment by shrekfx** [comment]
So, wanted to try  something else and downloaded and installed LDplayer.  The Tiny Clicker seems to be working fine with LDplayer, but I can't get it to work with bluestacks.

**Comment by filadog** [comment]
@shrekfx glad to know, thanks for the info. I will try to resolve the issue in the future, but it might take a while. Until then I suggest using LDPlayer if possible.

**Comment by filadog** [comment]
Hey @shrekfx, it took a while, but it seems I figured out the reason for your issue. You have to launch TinyClicker with administrator rights. Right click on app icon > "Run as administrator".
The reason for the issue is that BlueStacks app is launched under administrator by default on some systems, so TinyClicker is prohibited to interact with it.
